server:
  port: 8081 # Port for the auth-service

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/simple_auth} # Default for local, can be overridden by env var
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # For dev; use 'validate' or Flyway/Liquibase in prod
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # Optional: for debugging

# JWT Configuration (example, adjust names if different in monolith)
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:yourDefaultSecretKeyIfNotOverridden} # Use an environment variable for this!
      expiration: 86400000 # 1 day in ms
      refresh-token:
        expiration: 604800000 # 7 days in ms
