version: '3.8'

services:
  # Serviço do banco de dados PostgreSQL
  postgres:
    image: postgres:14
    container_name: simple-postgres
    environment:
      POSTGRES_DB: simple
      POSTGRES_USER: simple_user
      POSTGRES_PASSWORD: simple_password
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./database/sample_data.sql:/docker-entrypoint-initdb.d/sample_data.sql
    networks:
      - simple-network
    restart: unless-stopped

  # Serviço do backend Spring Boot
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: simple-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/simple
      SPRING_DATASOURCE_USERNAME: simple_user
      SPRING_DATASOURCE_PASSWORD: simple_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "9080:8080"
    networks:
      - simple-network
    restart: unless-stopped

  # Serviço do frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: simple-frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:9080
    ports:
      - "3000:3000"
    networks:
      - simple-network
    restart: unless-stopped

# Volumes para persistência de dados
volumes:
  postgres-data:
    name: simple-postgres-data

# Rede para comunicação entre os containers
networks:
  simple-network:
    name: simple-network
    driver: bridge
