spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Authentication Service (placeholder: http://localhost:8081)
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081} 
          predicates:
            - Path=/api/auth/**
        - id: users-service # For /api/users/**
          uri: ${AUTH_SERVICE_URL:http://localhost:8081} 
          predicates:
            - Path=/api/users/**

        # Citizen Service (placeholder: http://localhost:8082)
        - id: citizen-service
          uri: ${CITIZEN_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/cidadaos/**

        # Order Service (placeholder: http://localhost:8083)
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/pedidos/**

        # Configuration Service (placeholder: http://localhost:8084)
        - id: config-service-tipos # Tipos de Servicos
          uri: ${CONFIG_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/tipos-servicos/**
        - id: config-service-categorias # Categorias de Servicos
          uri: ${CONFIG_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/categorias-servicos/**
        - id: config-service-configs # /configuracoes (general app configs)
          uri: ${CONFIG_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/configuracoes

        # Favorites Service (placeholder: http://localhost:8085)
        - id: favorites-service
          uri: ${FAVORITES_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/favoritos/**
server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# Disable Eureka client
eureka:
  client:
    enabled: false
