spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Authentication Service (placeholder: http://localhost:8081)
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081} 
          predicates:
            - Path=/auth/**
        - id: auth-service-direct # For direct /auth/** paths (without /api prefix)
          uri: ${AUTH_SERVICE_URL:http://localhost:8081} 
          predicates:
            - Path=/auth/**
        - id: users-service # For /api/users/**
          uri: ${AUTH_SERVICE_URL:http://localhost:8081} 
          predicates:
            - Path=/users/**
          # Route for /perfis/**
        - id: auth-service-perfis
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/perfis/**

        # Citizen Service (placeholder: http://localhost:8082)
        - id: citizen-service
          uri: ${CITIZEN_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/utentes/**

        # Order Service (placeholder: http://localhost:8083)
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/pedidos/**

        # Configuration Service (placeholder: http://localhost:8084)
        - id: config-service-tipos # Tipos de Servicos
          uri: ${CONFIG_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/tipos-servicos/**
        - id: config-service-categorias # Categorias de Servicos
          uri: ${CONFIG_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/categorias-servicos/**
        - id: config-service-configs # /configuracoes (general app configs)
          uri: ${CONFIG_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/configuracoes
        - id: config-service-etapas
          uri: ${CONFIG_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/etapas-processo/**
        - id: config-service-status-pedidos
          uri: ${CONFIG_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/status-pedidos/**
        - id: config-service-tipos-documento
          uri: ${CONFIG_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/tipos-documento/**
        - id: config-service-lotes
          uri: ${CONFIG_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/lotes/**
        # Favorites Service (placeholder: http://localhost:8085)
        - id: favorites-service
          uri: ${FAVORITES_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/favoritos/**
server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# Disable Eureka client
eureka:
  client:
    enabled: false
