server:
  port: ${SERVER_PORT:8082} # Port for the citizen-service

spring:
  application:
    name: citizen-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/simple}
    username: ${SPRING_DATASOURCE_USERNAME:simple_user}
    password: ${SPRING_DATASOURCE_PASSWORD:simple_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # For dev
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # Optional

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs